language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

branches:
  except:
    - gh-pages

before_script:
  - touch app/database/database.sqlite
  - composer install -n --prefer-source
  - php artisan migrate --seed -n
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
